[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

# Performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# PWA Support
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"

# SPA routing for PWA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Gzip compression
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Encoding = "gzip"

# Security headers for monetization
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' *; script-src 'self' 'unsafe-inline' 'unsafe-eval' * blob: data:; connect-src 'self' * blob:; frame-src 'self' *; style-src 'self' 'unsafe-inline' *; img-src 'self' data: blob: *; font-src 'self' data: *;"

# Environment specific settings
[context.production.environment]
  SOCIAL_AUTOMATION = "enabled"
  CROSS_PROMOTION = "enabled"
  ANALYTICS_DEBUG = "false"

[context.deploy-preview.environment]
  SOCIAL_AUTOMATION = "disabled"
  CROSS_PROMOTION = "enabled"
  ANALYTICS_DEBUG = "true"

